import { readFile } from 'node:fs/promises'
import { describe, expect, test } from 'vitest'

const guidePath = 'packages/content/docs/DATA_SOURCE_ADAPTER_GUIDE.md'
const examplePath = 'test/fixtures/typecheck/types/data-source-adapter.ts'
const apiReferencePath = 'docs/content/docs/5.reference/11.package-exports.md'
const normalizeLineEndings = (value: string) => value.replace(/\r\n?/g, '\n')

describe('data-source adapter documentation', () => {
  test('publishes one complete adapter-author guide', async () => {
    const [guide, example] = await Promise.all([
      readFile(guidePath, 'utf8'),
      readFile(examplePath, 'utf8'),
    ])

    const normalizedGuide = guide.toLowerCase().replace(/\s+/g, ' ')
    for (const required of [
      '@lupinum/ginko-content/data-source',
      'verified context',
      'fixed-shape',
      'ginko portability codec',
      'persistence, authorization, byte streaming, and retry policy',
      'level 1',
      'level 2',
      'bindcontentprovider',
      'without workspace resolution',
      'production checklist',
    ]) {
      expect(normalizedGuide, required).toContain(required)
    }

    expect(normalizeLineEndings(guide)).toContain(
      `\`\`\`ts [data-source-adapter.ts]\n${normalizeLineEndings(example).trim()}\n\`\`\``
    )
  })

  test('publishes generated manifest and declaration API facts', async () => {
    const apiReference = await readFile(apiReferencePath, 'utf8')

    expect(apiReference).toContain('This file is generated by `pnpm api-docs:generate`.')
    expect(apiReference).toContain('| `@lupinum/ginko-content/data-source` |')
    expect(apiReference).toContain('| `@lupinum/ginko-content/testing/data-source-contract` |')
    expect(apiReference).toContain('| `ContentDataSource` | interface |')
    expect(apiReference).toContain('| `CONTENT_DATA_SOURCE_LIMITS` | const |')
  })
})
