export { __ginkoI18nBrand, __ginkoSchemaBrand, agentMetadataFields, defineAgentAppPage, defineAgentMarkdownPolicy, defineAgentMetadataFields, defineAgentSection, defineCollection, defineContentConfig, reference } from './types/config.js'
export { fields, getContentFieldMetadata, isContentFieldSchema } from './types/fields.js'
export { slugifyUrlSegment } from './core/content/slug.js'
export type { AgentMetadataField, AgentMetadataFieldList, CollectionSchema, ContentAgentCollectionConfig, ContentAgentMarkdownOptions, ContentCmsCollectionConfig, ContentCmsFieldConfig, ContentCmsFieldType, ContentCmsRelationConfig, ContentCollectionConfig, ContentCollectionI18nConfig, ContentCollectionKind, ContentCollectionSource, ContentCollectionSourceObject, ContentConfig, ContentReferenceSchema, DefineCollectionObject, DefineCollectionOptions } from './types/config.js'
export type { ContentFieldMetadata, ContentFieldSchema } from './types/fields.js'
export type { SlugifyUrlSegmentOptions } from './core/content/slug.js'
